output: content
paths:
  uploads: content/images
  static: content
collections_config:
  blog:
    path: content/blog
    output: false
    icon: rss_feed
    preview:
      subtext:
        - key: author
      gallery:
        image:
          - key: thumb_image_path
        fit: cover
    _enabled_editors:
      - visual
      - data
    _inputs:
      author:
        type: select
        options:
          allow_empty: true
          values: collections.profiles
          value_key: name
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url: /blog-post-previewer/
  profiles:
    path: content/profiles
    output: false
    icon: account_circle
    preview:
      subtext:
        - key: designation
      gallery:
        image:
          - key: image
        fit: contain
    _enabled_editors:
      - visual
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url: /profile-previewer/
  locations:
    path: content/locations
    output: false
    icon: fmd_good
    preview:
      subtext:
        - key: city
      gallery:
        image:
          - key: image
        fit: cover
    _enabled_editors:
      - visual
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url: /location-previewer/
  data:
    path: data
    output: false
    icon: pie_chart
    _enabled_editors:
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
collection_groups:
  - heading: Collections
    collections:
      - blog
      - profiles
      - locations
  - heading: Data
    collections:
      - data
_inputs:
  location:
    type: select
    options:
      allow_empty: true
      values: collections.locations
      value_key: title
    cascade: true
  city:
    type: select
    options:
      allow_empty: true
      values: data.cities
    cascade: true
  country:
    type: select
    options:
      allow_empty: true
      values: data.countries
    cascade: true
_select_data: {}
_structures: {}
_editables: {}
data_config:
  cities:
    path: data/cities.json
    parser:
  countries:
    path: data/countries.json
    parser: json
timezone: Etc/UTC
