# TODO: How to add schemas when they're json

collections_config:
  blog:
    path: content/blog
    icon: rss_feed
    output: false # Tell CloudCannon to not assign output URLS to this collection, so that the `new_preview_url` is used instead
    new_preview_url: /blog-post-previewer/ # Use the previewer page to preview all files in this collection
    _enabled_editors: # Prefer opening these files in the Visual Editor
      - visual
      - data
    preview:
      subtext:
        - key: author
      gallery:
        image:
          - key: thumb_image_path
        fit: cover
  profiles:
    path: content/profiles
    icon: account_circle
    output: false # Tell CloudCannon to not assign output URLS to this collection, so that the `new_preview_url` is used instead
    new_preview_url: /profile-previewer/ # Use the previewer page to preview all files in this collection
    _enabled_editors: # Prefer opening these files in the Visual Editor
      - visual
      - data
    preview:
      subtext:
        - key: designation
      gallery:
        image:
          - key: image
        fit: contain
  locations:
    path: content/locations
    icon: fmd_good
    output: false # Tell CloudCannon to not assign output URLS to this collection, so that the `new_preview_url` is used instead
    new_preview_url: /location-previewer/ # Use the previewer page to preview all files in this collection
    _enabled_editors: # Prefer opening these files in the Visual Editor
      - visual
      - data
    preview:
      subtext:
        - key: city
      gallery:
        image:
          - key: image
        fit: cover
  data:
    path: data
    icon: pie_chart
    output: false
    _enabled_editors:
      - data

output: content # Use the content folder as both the input and output directory of our build

data_config:
  cities:
    path: data/cities.json
  countries:
    path: data/countries.json
    parser: json

collection_groups:
  - heading: Collections
    collections:
      - blog
      - profiles
      - locations
  - heading: Data
    collections:
      - data

_inputs:
  location:
    type: select
    options:
      values: collections.locations
      value_key: title
  city:
    type: select
    options:
      values: data.cities
  country:
    type: select
    options:
      values: data.countries
      